- platform: ampio
  name: s_socket_terrace
  item: 0x241b/bin_output/6

- platform: ampio
  name: flag_wc_occupied
  item: 0x1f55/flag/32
  friendly_name: WC Zajęte

- platform: ampio
  name: s_recu_humidity
  item: 0x241b/bin_output/1

- platform: ampio
  name: s_recu_ventilation
  item: 0x241b/bin_output/2

- platform: ampio
  name: s_recu_high_co2
  item: 0x241b/bin_output/3

  
- platform: template
  switches:
    developer_mode:
        friendly_name: Developer Mode
        value_template: "{{states.group.developer.attributes.view == True}}"
        turn_on:
          - service: python_script.populate_catchall_group
          - service: python_script.find_unused_entities
          - service: group.set
            data:
              object_id: developer
              view: true
              visible: true
        turn_off:
          - service: group.set
            data:
              object_id: developer
              view: false
              visible: false
          - service: group.remove
            data:
              object_id: catchall
          - service: group.remove
            data:
              object_id: deaditems
