homeassistant:
  # Name of the location where Home Assistant is running
  name: Dom
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 273
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Warsaw
  # Customization file
  customize: !include customize.yaml
  
  packages:
    occupation: !include packages/occupation.yaml
    motion: !include packages/motion.yaml
    buderus: !include packages/buderus.yaml
    alarm: !include packages/alarm.yaml
    smog: !include packages/smog.yaml
    wc: !include packages/wc.yaml
    salon: !include packages/salon.yaml
    kitchen: !include packages/kitchen.yaml
  
  whitelist_external_dirs:
    - '/tmp/'

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

logger:
  default: warning 
  logs:
    homeassistant.components: warning
    pyampio: warning

telegram_bot:
  - platform: polling
    api_key: !secret telegram_boot_api_key
    allowed_chat_ids:
      - 509574229

recorder:
  purge_interval: 2
  purge_keep_days: 5
  exclude:
    domains:
      - automation
      - updater
      - camera

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
#updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

ios:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

influxdb:
  database: hass
  default_measurement: state
  exclude:
    domains:
      - automation
  tags:
    instance: prod
    source: hass


tts:
  - platform: amazon_polly
    aws_access_key_id: !secret aws_access_key_id
    aws_secret_access_key: !secret aws_secret_access_key
    voice: Ewa
    text_type: ssml


    
# Cloud
cloud:

hassio:

# apple_tv:
#  - host: apple-tv1

ffmpeg:

weather:
  - platform: darksky
    api_key: !secret dark_sky


notify:
  - name: Mr Homn
    platform: ciscospark
    token: !secret ciscospark_token
    roomid: !secret ciscospark_roomid
  
  - name: Telegram
    platform: telegram
    chat_id: 509574229

  - name: iphones
    platform: group
    services:
      - service: ios_petronella_bogini
      - service: ios_emperor

mqtt:
  broker: !secret cloudmqtt_server
  port: !secret cloudmqtt_port 
  client_id: hass_master
  keepalive: 60
  username: !secret cloudmqtt_user
  password: !secret cloudmqtt_pass

mqtt_eventstream:
  subscribe_topic: slaves/#
  publish_topic: master
  

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml


doorbird:
  host: 172.31.11.101
  username: !secret doorbird_username
  password: !secret doorbird_password
  doorbell_events: true
  

ampio:
  port: /dev/ttyUSB0
  autoconfig:
    - module: MULTISENS
      items:
        - name: temperature
          begin: 1
          end: 1
        - name: humidity
          begin: 1
          end: 1
        - name: mean-sea-level-pressure
          begin: 1
          end: 1
      use_module_name: yes
    - module: MCON-232SATEL
      items:
        # - name: bin_input
        #   begin: 1
        #   end: 11
        - name: bin_output
          begin: 1
          end: 16
        - name: armed
          begin: 1
          end: 3
        - name: alarm
          begin: 1
          end: 3
        - name: breached
          begin: 1
          end: 3
        - name: arming
          begin: 1
          end: 3
        - name: arming10s
          begin: 1
          end: 3


cover: !include_dir_merge_list covers
climate: !include_dir_merge_list climates
camera: !include_dir_merge_list cameras
binary_sensor: !include_dir_merge_list binary_sensors
media_player: !include_dir_merge_list media_players
light: !include_dir_merge_list lights
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches
input_boolean: !include_dir_merge_named input_booleans
input_select: !include_dir_merge_named input_selects

alarm_control_panel:
  - platform: ampio
    name: a_ground_floor
    item: 0x00001ecc/.*/1
    friendly_name: Strefa Parteru
    arm_away: yes

  - platform: ampio
    name: a_upper_floor
    item: 0x00001ecc/.*/2
    friendly_name: Strefa Piętra
    arm_away: yes

  - platform: ampio
    name: a_outside
    item: 0x00001ecc/.*/3
    friendly_name: Strefa Zewnętrzna
    arm_home: yes
    arm_away: yes

history_graph:
 smog:
   name: Smog
   entities:
     - sensor.smog_pm_10
     - sensor.smog_pm_25
   hours_to_show: 48
   refresh: 60
 
device_tracker:
  - platform: owntracks
  
  - platform: mqtt
    devices:
      klaudiusz_iphone: 'location/Emperor'
      julia_iphone: 'location/iPhone-Julia'
      agnieszka_iphone: 'location/PetronelaBogini'
      alicja_iphone: 'location/Jace'
    
    
  
  
#   - platform: cisco_ios
#     host: 172.31.11.254
#     username: !secret switch_username
#     password: !secret switch_password
 
# bmw_connected_drive:
#   mycar:
#     username: !secret connected_drive_username
#     password: !secret connected_drive_password
#     country: Poland

homekit:
  pincode: '333-44-333'    

zone:
  - name: home
    track_ios: true
    icon: mdi:account-multiple
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 50
    passive: true
    
  - name: Gabinet
    track_ios: true
    icon: mdi:account-multiple
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 50
    passive: true
    
  - name: Kuchnia
    track_ios: true
    icon: mdi:stove
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 50
    passive: true
    
  - name: Galeria
    latitude: 50.302682
    longitude: 19.017649
    radius: 100
    icon: mdi:mdi-factory
    track_ios: true
  
  - name: Szkoła Emilki
    latitude: 50.3009454
    longitude: 19.0069752
    radius: 500
    icon: mdi:mdi-school
    track_ios: true
    
  - name: Medicover Graniczna
    latitude: 50.2456947
    longitude: 19.0355328
    radius: 100
    icon: mdi:mdi-hospital
    track_ios: true
    
  - name: Medicover Chorzowska
    latitude: 50.2657004
    longitude: 19.0136452
    radius: 100
    icon: mdi:mdi-hospital
    track_ios: true
    
  - name: Stańki
    latitude: 50.1834112
    longitude: 19.1325946
    radius: 500
    icon: mdi:mdi-human-male-female
    track_ios: true
    
  - name: Koniory
    latitude: 49.8424449
    longitude: 19.0634458
    radius: 500
    icon: mdi:mdi-human-male-female
    track_ios: true
    
    
    

