# WC


- platform: group
  name: l_wc
  entities:
  - light.l_wc_mled1
  - light.l_wc_mled2
  - light.l_wc_led
  
- platform: group
  name: l_kitchen
  entities:
  - light.l_kitchen_mled1
  - light.l_kitchen_mled2
  - light.l_kitchen_mled3
  - light.l_kitchen_mled4
  - light.l_kitchen_mled5
  - light.l_kitchen_mled6
  - light.l_kitchen_mled7
  - light.l_kitchen_mled8
  - light.l_kitchen_mled9
  - light.l_kitchen_mled10
  - light.l_kitchen_workbench
  
- platform: group
  name: l_salon_mled
  entities:
  - light.l_salon_mled1
  - light.l_salon_mled2  
  - light.l_salon_mled3  
  - light.l_salon_mled4  
  - light.l_salon_mled5  
  - light.l_salon_mled6  
  - light.l_salon_mled7  
  - light.l_salon_mled8  
  - light.l_salon_mled9  
  - light.l_salon_mled10  
  - light.l_salon_mled11 
  - light.l_salon_mled12
  
- platform: group
  name: l_sofa_mled
  entities:
  - light.l_sofa_mled1
  - light.l_sofa_mled2
  - light.l_sofa_mled3
  - light.l_sofa_mled4
  - light.l_sofa_mled5
  - light.l_sofa_mled6

- platform: group
  name: l_hol_mled
  entities:
  - light.l_hol_mled1
  - light.l_hol_mled2
  - light.l_hol_mled3
  - light.l_hol_mled4
  

- platform: ampio
  name: l_wc_mled1
  item: 0x1e53/bin_output/7
  bright_item: 0x1e53/output/7

- platform: ampio
  name: l_wc_mled1
  item: 0x1e53/bin_output/8
  bright_item: 0x1e53/output/8

- platform: ampio
  name: l_wc_led
  item: 0x1885/bin_output/3
  bright_item: 0x1885/output/3

# Master bathroom
- platform: ampio
  name: l_master_bathroom_mled1
  item: 0x1e5a/bin_output/1
  bright_item: 0x1e5a/bin_output/1

- platform: ampio
  name: l_master_bathroom_mled2
  item: 0x1e5a/bin_output/2
  bright_item: 0x1e5a/bin_output/2

- platform: ampio
  name: l_master_bathroom_mled3
  item: 0x1e5a/bin_output/3
  bright_item: 0x1e5a/bin_output/3

- platform: ampio
  name: l_master_bathroom_mled4
  item: 0x1e5a/bin_output/4
  bright_item: 0x1e5a/bin_output/4

- platform: ampio
  name: l_master_bathroom_mled5
  item: 0x1e5a/bin_output/5
  bright_item: 0x1e5a/bin_output/5

- platform: ampio
  name: l_master_bathroom_mled6
  item: 0x1e5a/bin_output/6
  bright_item: 0x1e5a/bin_output/6

- platform: ampio
  name: l_master_bathroom_mled7
  item: 0x1e5a/bin_output/7
  bright_item: 0x1e5a/bin_output/7

- platform: ampio
  name: l_master_bathroom_mled8
  item: 0x1e5a/bin_output/8
  bright_item: 0x1e5a/bin_output/8

- platform: ampio
  name: l_master_bathroom_mled9
  item: 0x1e5a/bin_output/9
  bright_item: 0x1e5a/bin_output/9

- platform: ampio
  name: l_master_bathroom_mled10
  item: 0x1e5a/bin_output/10
  bright_item: 0x1e5a/bin_output/10
  
- platform: ampio
  name: l_masterbathroom_led
  item: 0x1885/bin_output/1
  bright_item: 0x1885/output/1
  
- platform: ampio
  name: l_rgb_bathtub
  item: 0x18b2/bin_.*/1
  rgb_item: 0x18b2/color_.*/1
  white_item: 0x18b2/output/1


# Bathroom
- platform: ampio
  name: l_bathroom_mled11
  item: 0x1e5a/bin_output/11
  bright_item: 0x1e5a/bin_output/11

- platform: ampio
  name: l_bathroom_mled12
  item: 0x1e5a/bin_output/12
  bright_item: 0x1e5a/bin_output/12

- platform: ampio
  name: l_bathroom_mled13
  item: 0x1e5a/bin_output/13
  bright_item: 0x1e5a/bin_output/13

- platform: ampio
  name: l_bathroom_mled14
  item: 0x1e5a/bin_output/14
  bright_item: 0x1e5a/bin_output/14

- platform: ampio
  name: l_bathroom_mled15
  item: 0x1e5a/bin_output/15
  bright_item: 0x1e5a/bin_output/15

- platform: ampio
  name: l_bathroom_mled16
  item: 0x1e5a/bin_output/16
  bright_item: 0x1e5a/bin_output/16
  
- platform: ampio
  name: l_bathroom_led
  item: 0x1885/bin_output/2
  bright_item: 0x1885/output/2

# Salon
- platform: ampio
  name: l_salon_mled1
  item: 0x1e5d/bin_output/1
  bright_item: 0x1e5d/bin_output/1

- platform: ampio
  name: l_salon_mled2
  item: 0x1e5d/bin_output/2
  bright_item: 0x1e5d/bin_output/2

- platform: ampio
  name: l_salon_mled3
  item: 0x1e5d/bin_output/3
  bright_item: 0x1e5d/bin_output/3

- platform: ampio
  name: l_salon_mled4
  item: 0x1e5d/bin_output/4
  bright_item: 0x1e5d/bin_output/4

- platform: ampio
  name: l_salon_mled5
  item: 0x1e5d/bin_output/5
  bright_item: 0x1e5d/bin_output/5

- platform: ampio
  name: l_salon_mled6
  item: 0x1e5d/bin_output/6
  bright_item: 0x1e5d/bin_output/6

- platform: ampio
  name: l_salon_mled7
  item: 0x1e5d/bin_output/7
  bright_item: 0x1e5d/bin_output/7

- platform: ampio
  name: l_salon_mled8
  item: 0x1e5d/bin_output/8
  bright_item: 0x1e5d/bin_output/8

- platform: ampio
  name: l_salon_mled9
  item: 0x1e5d/bin_output/9
  bright_item: 0x1e5d/bin_output/9

- platform: ampio
  name: l_salon_mled10
  item: 0x1e5d/bin_output/10
  bright_item: 0x1e5d/bin_output/10

- platform: ampio
  name: l_salon_mled11
  item: 0x1e5d/bin_output/11
  bright_item: 0x1e5d/bin_output/11

- platform: ampio
  name: l_salon_mled12
  item: 0x1e5d/bin_output/12
  bright_item: 0x1e5d/bin_output/12

# Salon sofa 
- platform: ampio
  name: l_sofa_mled1
  item: 0x1e5f/bin_output/11
  bright_item: 0x1e5f/bin_output/11

- platform: ampio
  name: l_sofa_mled2
  item: 0x1e5f/bin_output/12
  bright_item: 0x1e5f/bin_output/12

- platform: ampio
  name: l_sofa_mled3
  item: 0x1e5f/bin_output/13
  bright_item: 0x1e5f/bin_output/13
  
- platform: ampio
  name: l_sofa_mled4
  item: 0x1e5f/bin_output/14
  bright_item: 0x1e5f/bin_output/14
  
- platform: ampio
  name: l_sofa_mled5
  item: 0x1e5f/bin_output/15
  bright_item: 0x1e5f/bin_output/15
  
- platform: ampio
  name: l_sofa_mled6
  item: 0x1e5f/bin_output/16
  bright_item: 0x1e5f/bin_output/16
 
# Salon RGB
- platform: ampio
  name: rgb_salon
  item: 0x1879/bin_.*/1
  rgb_item: 0x1879/color_.*/1
  white_item: 0x1879/output/1

- platform: ampio
  name: rgb_stairs
  item: 0x1ab3/bin_.*/1
  rgb_item: 0x1ab3/color_.*/1
  white_item: 0x1ab3/output/1


# hol
- platform: ampio
  name: l_hol_mled1
  item: 0x1e5d/bin_output/13
  bright_item: 0x1e5d/bin_output/13

- platform: ampio
  name: l_hol_mled2
  item: 0x1e5d/bin_output/14
  bright_item: 0x1e5d/bin_output/14

- platform: ampio
  name: l_hol_mled3
  item: 0x1e5d/bin_output/15
  bright_item: 0x1e5d/bin_output/15

- platform: ampio
  name: l_hol_mled4
  item: 0x1e5d/bin_output/16
  bright_item: 0x1e5d/bin_output/16


# kitchen
- platform: ampio
  name: l_kitchen_mled1
  item: 0x1e5f/bin_output/1
  bright_item: 0x1e5f/bin_output/1

- platform: ampio
  name: l_kitchen_mled2
  item: 0x1e5f/bin_output/2
  bright_item: 0x1e5f/bin_output/2

- platform: ampio
  name: l_kitchen_mled3
  item: 0x1e5f/bin_output/3
  bright_item: 0x1e5f/bin_output/3

- platform: ampio
  name: l_kitchen_mled4
  item: 0x1e5f/bin_output/4
  bright_item: 0x1e5f/bin_output/4

- platform: ampio
  name: l_kitchen_mled5
  item: 0x1e5f/bin_output/5
  bright_item: 0x1e5f/bin_output/5

- platform: ampio
  name: l_kitchen_mled6
  item: 0x1e5f/bin_output/6
  bright_item: 0x1e5f/bin_output/6

- platform: ampio
  name: l_kitchen_mled7
  item: 0x1e5f/bin_output/7
  bright_item: 0x1e5f/bin_output/7

- platform: ampio
  name: l_kitchen_mled8
  item: 0x1e5f/bin_output/8
  bright_item: 0x1e5f/bin_output/8

- platform: ampio
  name: l_kitchen_mled9
  item: 0x1e5f/bin_output/9
  bright_item: 0x1e5f/bin_output/9

- platform: ampio
  name: l_kitchen_mled10
  item: 0x1e5f/bin_output/10
  bright_item: 0x1e5f/bin_output/10

# kitchen - dining
- platform: ampio
  name: l_dining_table
  item: 0x19c7/bin_output/8
  bright_item: 0x19c7/output/8

# salon - tubes
- platform: ampio
  name: l_salon_tubes
  item: 0x00001a1e/bin_output/1

# kitchen - workbench
- platform: ampio
  name: l_kitchen_workbench
  item: 0x00001a1e/bin_output/2
  
# engine_room
- platform: ampio
  name: l_engine_room
  item: 0x00001a1e/bin_output/7

# pictures
- platform: ampio
  name: l_pictures
  item: 0x00001a1e/bin_output/8
  


# office
- platform: ampio
  name: l_office
  item: 0x13ec/bin_output/5
  bright_item: 0x13ec/output/5

# server room
- platform: ampio
  name: l_server_room
  item: 0x1a1e/bin_output/4
  


