- platform: systemmonitor
  resources:
    - type: memory_free
    - type: memory_use_percent
    - type: memory_use
    - type: swap_use_percent
    - type: swap_use
    - type: swap_free

- platform: time_date
  display_options:
    - 'date_time'
