- platform: group
  name: c_office
  entities:
    - cover.c_office_north
    - cover.c_office_west

- platform: group
  name: c_kitchen
  entities:
    - cover.c_kitchen_north
    - cover.c_kitchen_east
    
- platform: group
  name: c_north
  entities:
    - cover.c_kitchen_north
    - cover.c_office_north
    - cover.c_masterbedroom_wardrobe
    - cover.c_masterbathroom

- platform: group
  name: c_east
  entities:
    - cover.c_kitchen_east
    - cover.c_emily
    
- platform: group
  name: c_south
  entities:
    - cover.c_livingroom
    - cover.c_julia
    - cover.c_washing
    - cover.c_alice
    
- platform: group
  name: c_west
  entities:
    - cover.c_livingroom_terrace
    - cover.c_bonsai
    - cover.c_masterbedroom
    - cover.c_office_west
    
- platform: group
  name: c_all
  entities:
    - cover.c_livingroom
    - cover.c_livingroom_terrace
    - cover.c_kitchen_north
    - cover.c_kitchen_east
    - cover.c_bonsai
    - cover.c_office_north
    - cover.c_office_west
    - cover.c_masterbedroom
    - cover.c_masterbedroom_wardrobe
    - cover.c_masterbathroom
    - cover.c_emily
    - cover.c_julia
    - cover.c_alice
    - cover.c_washing
    
- platform: group
  name: c_upstairs
  entities:
    - cover.c_masterbedroom
    - cover.c_masterbedroom_wardrobe
    - cover.c_masterbathroom
    - cover.c_emily
    - cover.c_julia
    - cover.c_alice
    - cover.c_washing
    
- platform: group
  name: c_downstairs
  entities:
    - cover.c_livingroom
    - cover.c_livingroom_terrace
    - cover.c_kitchen_north
    - cover.c_kitchen_east
    - cover.c_bonsai
    - cover.c_office_north
    - cover.c_office_west
    

- platform: ampio
  name: c_livingroom
  item: 0x196A/cover_position/1
  tilt_item: 0x196A/tilt_position/1

- platform: ampio
  name: c_livingroom_terrace
  item: 0x196A/cover_position/2
  tilt_item: 0x196A/tilt_position/2

- platform: ampio
  name: c_kitchen_north
  item: 0x196A/cover_position/3
  tilt_item: 0x196A/tilt_position/3

- platform: ampio
  name: c_kitchen_east
  item: 0x196A/cover_position/4
  tilt_item: 0x196A/tilt_position/4

- platform: ampio
  name: c_bonsai
  item: 0x1968/cover_position/1
  tilt_item: 0x1968/tilt_position/1

- platform: ampio
  name: c_office_north
  item: 0x1968/cover_position/2
  tilt_item: 0x1968/tilt_position/2

- platform: ampio
  name: c_office_west
  item: 0x1968/cover_position/3
  tilt_item: 0x1968/tilt_position/3

- platform: ampio
  name: c_masterbedroom
  item: 0x1968/cover_position/4
  tilt_item: 0x1968/tilt_position/4


- platform: ampio
  name: c_masterbedroom_wardrobe
  item: 0x1965/cover_position/1
  tilt_item: 0x1965/tilt_position/1

- platform: ampio
  name: c_masterbathroom
  item: 0x1965/cover_position/2
  tilt_item: 0x1965/tilt_position/2

- platform: ampio
  name: c_emily
  item: 0x1965/cover_position/3
  tilt_item: 0x1965/tilt_position/3

- platform: ampio
  name: c_julia
  item: 0x1965/cover_position/4
  tilt_item: 0x1965/tilt_position/4

- platform: ampio
  name: c_washing
  item: 0x1B2A/cover_position/1
  tilt_item: 0x1B2A/tilt_position/1

- platform: ampio
  name: c_alice
  item: 0x1B2A/cover_position/2
  tilt_item: 0x1B2A/tilt_position/2

- platform: ampio
  name: c_water_from_tank
  item: 0x1B2A/cover_position/3
  tilt_item: 0x1B2A/tilt_position/3

- platform: ampio
  name: c_garage_gate
  item: 0x1B2A/cover_position/4
  tilt_item: 0x1B2A/tilt_position/4

