automation:

  - alias: Play ambient music in Masterbathroom in the morning
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: input_select.room_masterbathroom_occupancy
      to: "Zajęty"
    condition:
      - condition: time
        after: '7:00'
        before: '11:00'
    action:
      - service: media_player.volume_set
        entity_id: media_player.azienka_krolewska
        data:
          volume_level: 0.15
          
      - service: media_player.play_media
        data:
          entity_id: media_player.azienka_krolewska
          media_content_type: PLAYLIST
        data_template:
          media_content_id: >
            {{ [ "http://dcs-193-111-38-243.atmcdn.pl/sc/o2/Eurozet/live/antyradio.livx?audio=5" ] | random}}
  
  - alias: Play ambient music in Masterbathroom in the day
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: input_select.room_masterbathroom_occupancy
      to: "Zajęty"
    condition:
      - condition: time
        after: '11:00'
        before: '20:00'
    action:
      - service: media_player.volume_set
        entity_id: media_player.azienka_krolewska
        data:
          volume_level: 0.1
      
      - service: media_player.play_media
        data:
          entity_id: media_player.azienka_krolewska
          media_content_type: PLAYLIST
        # "http://somafm.com/groovesalad130.pls", "http://somafm.com/dronezone130.pls"
        data_template:
          media_content_id: >
            {{ [ "http://somafm.com/spacestation130.pls" ] | random}}
  
  - alias: Stop ambient music in masterbathroom
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_select.room_masterbathroom_occupancy
        to: "Pusty"
        for:
          minutes: 1
      - platform: state
        entity_id: input_select.room_masterbathroom_occupancy
        to: "Nieznany"
        for:
          minutes: 1
    
    action:
      - service: media_player.turn_off
        data:
          entity_id: media_player.azienka_krolewska