homeassistant:
  customize:
    packages.motion_lights: &customize
      package: 'motion'

    input_select.last_motion_triggered:
      <<: *customize
      friendly_name: 'Ostatnio wykryto ruch w:'
      
    sensor.last_motion_triggered_name:
      <<: *customize
      friendly_name: "Ostatnio wykryto ruch:"
      
sensor:
  - platform: template
    sensors:
      last_motion_triggered_name:
        value_template: "{{ state_attr('binary_sensor.' + states('input_select.last_motion_triggered'), 'friendly_name') }}"

input_select:
  last_motion_triggered:
    initial: m_salon
    options:
      - m_salon
      - m_kitchen
      - m_wc
      - m_hall_groundfloor
      - m_antreroom
      - m_office
      - m_serverroom
      - m_pantry
      - m_wardrobe_ground
      - m_garage
      - m_garage_garden
      - m_curtain_groundfloor
      - m_curtain_firstfloor
      - m_julia
      - m_julia_wardrobe
      - m_masterbathroom
      - m_masterbedroom
      - m_masterbedroom_hall
      - m_hall_firstfloor
      - m_hall_firstfloor2
      - m_masterbedroom_wardrobe
      - m_emily
      - m_emily_wardrobe
      - m_alice
      - m_laundry
      - m_bathroom

automation:
  - alias: Update last motion triggered from motion sensors last triggered
    initial_state: 'on'
    trigger:
      platform: state
      entity_id:
        - binary_sensor.m_salon
        - binary_sensor.m_kitchen
        - binary_sensor.m_wc
        - binary_sensor.m_hall_groundfloor
        - binary_sensor.m_antreroom
        - binary_sensor.m_office
        - binary_sensor.m_serverroom
        - binary_sensor.m_pantry
        - binary_sensor.m_wardrobe_ground
        - binary_sensor.m_garage
        - binary_sensor.m_garage_garden
        - binary_sensor.m_curtain_groundfloor
        - binary_sensor.m_curtain_firstfloor
        - binary_sensor.m_julia
        - binary_sensor.m_julia_wardrobe
        - binary_sensor.m_masterbathroom
        - binary_sensor.m_masterbedroom
        - binary_sensor.m_masterbedroom_hall
        - binary_sensor.m_hall_firstfloor
        - binary_sensor.m_hall_firstfloor2
        - binary_sensor.m_masterbedroom_wardrobe
        - binary_sensor.m_emily
        - binary_sensor.m_emily_wardrobe
        - binary_sensor.m_alice
        - binary_sensor.m_laundry
        - binary_sensor.m_bathroom
      to: 'on'

    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.last_motion_triggered
          option: "{{ trigger.to_state.entity_id.split('.')[1] }}"
          
