

automation:
  - alias: Ruch w pokoju Julii
    initial_state: 'on'
    trigger:
      platform: state
      entity_id:
        - binary_sensor.m_julia
      to: "on"

    condition:
      condition: state
      entity_id: binary_sensor.d_julia
      state: "off"

    action:
      - service: input_select.select_option
        data_template:
          entity_id: "input_select.room_{{ trigger.entity_id | replace('binary_sensor.m_', '')}}_occupancy"
          option: "Zajęty"

  - alias: Ruch w pokoju Alicji
    initial_state: 'on'
    trigger:
      platform: state
      entity_id:
        - binary_sensor.m_alice
      to: "on"

    condition:
      condition: state
      entity_id: binary_sensor.d_alice
      state: "off"

    action:
      - service: input_select.select_option
        data_template:
          entity_id: "input_select.room_{{ trigger.entity_id | replace('binary_sensor.m_', '')}}_occupancy"
          option: "Zajęty"

  - alias: Ruch w pokoju Emilii
    initial_state: 'on'
    trigger:
      platform: state
      entity_id:
        - binary_sensor.m_emily
      to: "on"

    condition:
      condition: state
      entity_id: binary_sensor.d_emily
      state: "off"

    action:
      - service: input_select.select_option
        data_template:
          entity_id: "input_select.room_{{ trigger.entity_id | replace('binary_sensor.m_', '')}}_occupancy"
          option: "Zajęty"

  - alias: Ruch w WC
    initial_state: 'on'
    trigger:
      platform: state
      entity_id:
        - binary_sensor.m_wc
      to: "on"

    condition:
      condition: state
      entity_id: binary_sensor.d_wc
      state: "off"

    action:
      - service: input_select.select_option
        data_template:
          entity_id: "input_select.room_{{ trigger.entity_id | replace('binary_sensor.m_', '')}}_occupancy"
          option: "Zajęty"
          
  - alias: Ruch w Sypialni
    initial_state: 'on'
    trigger:
      platform: state
      entity_id:
        - binary_sensor.m_masterbedroom
      to: "on"

    condition:
      condition: state
      entity_id: binary_sensor.d_masterbedroom
      state: "off"

    action:
      - service: input_select.select_option
        data_template:
          entity_id: "input_select.room_{{ trigger.entity_id | replace('binary_sensor.m_', '')}}_occupancy"
          option: "Zajęty"
          
  - alias: Ruch w Dużej Łazience
    initial_state: 'on'
    trigger:
      platform: state
      entity_id:
        - binary_sensor.m_masterbathroom
      to: "on"

    condition:
      condition: state
      entity_id: binary_sensor.d_masterbathroom
      state: "off"

    action:
      - service: input_select.select_option
        data_template:
          entity_id: "input_select.room_{{ trigger.entity_id | replace('binary_sensor.m_', '')}}_occupancy"
          option: "Zajęty"
          
  - alias: Ruch w Łazience
    initial_state: 'on'
    trigger:
      platform: state
      entity_id:
        - binary_sensor.m_bathroom
      to: "on"

    condition:
      condition: state
      entity_id: binary_sensor.d_bathroom
      state: "off"

    action:
      - service: input_select.select_option
        data_template:
          entity_id: "input_select.room_{{ trigger.entity_id | replace('binary_sensor.m_', '')}}_occupancy"
          option: "Zajęty"

  - alias: Ruch w Biurze
    initial_state: 'on'
    trigger:
      platform: state
      entity_id:
        - binary_sensor.m_office
      to: "on"

    condition:
      condition: state
      entity_id: binary_sensor.d_office
      state: "off"

    action:
      - service: input_select.select_option
        data_template:
          entity_id: "input_select.room_{{ trigger.entity_id | replace('binary_sensor.m_', '')}}_occupancy"
          option: "Zajęty"

  - alias: Otwarcie drzwi
    initial_state: 'on'
    trigger:
      platform: state
      entity_id:
        - binary_sensor.d_julia
        - binary_sensor.d_alice
        - binary_sensor.d_emily
        - binary_sensor.d_wc
        - binary_sensor.d_masterbedroom
        - binary_sensor.d_masterbathroom
        - binary_sensor.d_office
        - binary_sensor.d_bathroom
      to: "on"

    action:
      - service: input_select.select_option
        data_template:
          entity_id: "input_select.room_{{ trigger.entity_id | replace('binary_sensor.d_', '')}}_occupancy"
          option: "Nieznany"

  - alias: Zamknięcie drzwi
    initial_state: 'on'
    trigger:
      platform: state
      entity_id:
        - binary_sensor.d_julia
        - binary_sensor.d_alice
        - binary_sensor.d_emily
        - binary_sensor.d_wc
        - binary_sensor.d_masterbedroom
        - binary_sensor.d_masterbathroom
        - binary_sensor.d_office
        - binary_sensor.d_bathroom
      to: "off"

    action:
      - service: input_select.select_option
        data_template:
          entity_id: "input_select.room_{{ trigger.entity_id | replace('binary_sensor.d_', '')}}_occupancy"
          option: "Pusty"
