scene:
  - name: Ambient Light Off
    entities: 
      light.rgb_stairs:
        state: off
      light.rgb_salon:
        state: off
  
  - name: Ambient Light Morning
    entities: 
      light.rgb_stairs:
        state: on
        rgb_color: [0,0,255]
        white_value: 0
      light.rgb_salon:
        state: on
        rgb_color: [0,0,255]
        white_value: 0
    
  - name: Ambient Light Night
    entities: 
      light.rgb_stairs:
        state: on
        rgb_color: [255,128,0]
        white_value: 0
      light.rgb_salon:
        state: on
        rgb_color: [255,128,0]
        white_value: 0
        
  - name: Ambient Light Evening
    entities: 
      light.rgb_stairs:
        state: on
        rgb_color: [128,64,0]
        white_value: 0
      light.rgb_salon:
        state: on
        rgb_color: [128,64,0]
        white_value: 0
  
  - name: Ambient Light Dusk
    entities: 
      light.rgb_stairs:
        state: on
        rgb_color: [96,32,0]
        white_value: 0
      light.rgb_salon:
        state: on
        rgb_color: [96,32,0]
        white_value: 0


automation:
  - alias: Sunset
    trigger:
      platform: sun
      event: sunset
    action:
      service: tts.amazon_polly_say
      entity_id: media_player.mpd_kitchen
      data:
        message: "<speak>Zachód słońca.</speak>"
        
  - alias: Sunrise
    trigger:
      platform: sun
      event: sunrise
    action:
      - service: scene.turn_on
        entity_id: scene.ambient_light_morning
        
  - alias: Ambient Off
    trigger:
      platform: time
      at: "11:10:00"
    action:
      - service: automation.turn_on
        entity_id: automation.turn_a_few_lights_on_when_the_sun_gets_dim
      - service: scene.turn_on
        entity_id: scene.ambient_light_off
      
  - alias: 'Turn a few lights on when the sun gets dim'
    trigger:
      platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 3.5
  
    action:
      - service: automation.turn_off
        entity_id: automation.turn_a_few_lights_on_when_the_sun_gets_dim
      - service: scene.turn_on
        entity_id: scene.ambient_light_dusk
  
  - alias: 'Turn more lights on as the sun gets dimmer'
    trigger:
      platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 1.5
  
    action:
      - service: automation.turn_off
        entity_id: automation.turn_more_lights_on_as_the_sun_gets_dimmer
      - service: scene.turn_on
        entity_id: scene.ambient_light_evening
      
  - alias: 'Dark'
    trigger:
      platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: -5.0
    
    action:
      - service: automation.turn_off
        entity_id: automation.dark
      - service: scene.turn_on
        entity_id: scene.ambient_light_night
        
  - alias: 'No move after midnight'
    trigger:
      platform: time
      # every 1 minutes
      minutes: '/1'
      seconds: 00
    condition:
      - condition: time
        after: '00:00:01'
        before: '05:00:00'
      - condition: state
        entity_id: binary_sensor.m_salon
        state: 'off'
        for:
          minutes: 30
      
    action:
      - service: light.turn_off
        data:
          entity_id:
            - light.rgb_stairs
            - light.rgb_salon
            - light.l_kitchen_mled1
            - light.l_kitchen_mled2
            - light.l_kitchen_mled3
            - light.l_kitchen_mled4
            - light.l_kitchen_mled5
            - light.l_kitchen_mled6
            - light.l_kitchen_mled7
            - light.l_kitchen_mled8
            - light.l_kitchen_mled9
            - light.l_kitchen_mled10


  - alias: 'Turn the hall lights off if no move' 
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: binary_sensor.m_hall_groundfloor
      to: "off"
      for:
        minutes: 5
    action:
      - service: light.turn_off
        data:
          entity_id:
            - light.l_hol_mled1
            - light.l_hol_mled2
            - light.l_hol_mled3
            - light.l_hol_mled4
            
              
