sensor:
  - platform: rest
    name: SMOG
    json_attributes:
      - CZAS
      - PM25
      - PM10
      - ID
      - humidity
      - pressure
    resource: http://smog1.ampio.pl:3050/api/data/16/detail/lastrecord
    value_template: '{{ value_json.CZAS }}'
    # {"CZAS":"2018-01-29 06:00:56","PM25":54,"PM10":75,"ID":5167433,"humidity":76.613998,"pressure":988.02002}
    force_update: true
    
  - platform: template
    sensors:
      smog_pm_25:
        friendly_name: PM25
        value_template: '{{ states.sensor.smog.attributes["PM25"] | round(0) }}'
        unit_of_measurement: 'µg/m³'
      smog_pm_10:
        friendly_name: PM10
        value_template: '{{ states.sensor.smog.attributes["PM10"] | round(0) }}'
        unit_of_measurement: 'µg/m³'
      smog_humidity:
        friendly_name: Wilgotność
        value_template: '{{ states.sensor.smog.attributes["humidity"] | round(0) }}'
        unit_of_measurement: '%'
      smog_pressure:
        friendly_name: Ciśnienie
        value_template: '{{ states.sensor.smog.attributes["pressure"] | round(0) }}'
        unit_of_measurement: 'hPa'
        
  - platform: rest
    name: antistorm
    json_attributes:
      - m
      - p_b
      - t_b
      - a_b
      - p_o
      - t_o
      - a_o
      - s
    resource: http://antistorm.eu/webservice.php?id=312
    value_template: "{{ value_json.m }}"
    force_update: true
  
  - platform: template
    sensors:
      storm_prob:
        friendly_name: Prawdopodobieństwo burzy
        value_template: '{{ states.sensor.antistorm.attributes["p_b"] }}'
      rain_prob:
        friendly_name: Prawdopodobieństwo opdaów
        value_template: '{{ states.sensor.antistorm.attributes["p_o"] }}'
        
homeassistant:
  customize:
    input_select.smog_pm10_level:
      friendly_name: 'Stężenie pyłu zawieszonego PM10'


input_select:
  smog_pm10_level:
    initial: Poziom Dopuszczaly (<50 µg/m³)
    options:
      - Poziom Dopuszczaly (<50 µg/m³)
      - Poziom Podwyższony (50-200 µg/m³)
      - Poziom Informowania (200-300 µg/m³)
      - Poziom Alarmowy (300+ µg/m³)
    
      
automation:
  - alias: Smog Level Podwyzszony
    trigger:
      platform: state
      entity_id: input_select.smog_pm10_level
      to: 'Podwyższony (50-200 µg/m³)'
    action:
      - service: tts.amazon_polly_say
        entity_id: 
          - media_player.mpd_kitchen
        data:
          message: "Uwaga! Podwyższony poziom pyłu zawieszonego."
  
  - alias: Smog Level Informacja
    trigger:
      platform: state
      entity_id: input_select.smog_pm10_level
      to: 'Informowania (200-300 µg/m³)'
    action:
      - service: tts.amazon_polly_say
        entity_id: 
          - media_player.mpd_kitchen
        data:
          message: "Uwaga! Poziom pyłu zawieszonego znacznie przekroczony."
          
  - alias: Smog Level Alarm
    trigger:
      platform: state
      entity_id: input_select.smog_pm10_level
      to: 'Poziom Alarmowy (300+ µg/m³)'
    action:
      - service: tts.amazon_polly_say
        entity_id: 
          - media_player.mpd_kitchen
        data:
          message: "Uwaga! Poziom pyłu zawieszonego znacznie przekroczył poziom alarmowy."
        
      
  - alias: Smog Poziom Dopuczalny
    initial_state: 'on'
    trigger:
      platform: template
      value_template: "{{ states.sensor.smog_pm_10.state | int <= 50 }}"
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.smog_pm10_level
          option: Poziom Dopuszczaly (<50 µg/m³)
  
  - alias: Smog Poziom Podwyższony
    initial_state: 'on'
    trigger:
      platform: template
      value_template: "{{ states.sensor.smog_pm_10.state | int > 50 and states.sensor.smog_pm_10.state | int <= 200 }}"
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.smog_pm10_level
          option: Poziom Podwyższony (50-200 µg/m³)
  
  - alias: Smog Poziom Informowania
    initial_state: 'on'
    trigger:
      platform: template
      value_template: "{{ states.sensor.smog_pm_10.state | int > 200 and states.sensor.smog_pm_10.state | int <= 300 }}"
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.smog_pm10_level
          option: Poziom Informowania (200-300 µg/m³)
          
  - alias: Smog Poziom Alarmowy
    initial_state: 'on'
    trigger:
      platform: template
      value_template: "{{ states.sensor.smog_pm_10.state | int > 300 }}"
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.smog_pm10_level
          option: Poziom Alarmowy (300+ µg/m³)
          
  - alias: Telegram Bot
    initial_state: 'on'
    trigger:
      platform: event
      event_type: telegram_command
      event_data:
        command: '/smog'
    action:
      - service: telegram_bot.send_message
        data_template:
          title: '*Raport Smogowy*'
          target: '{{ trigger.event.data.user_id }}'
          message: "Aktualny pomiar z {{ states.sensor.smog.state }}
          
          
            Stężenie PM10: {{ states.sensor.smog_pm_10.state }} µg/m³
            
            Stężenie PM25: {{ states.sensor.smog_pm_25.state }} µg/m³
            
            Wilgotność: {{ states.sensor.smog_humidity.state }} %"
            
