automation:

  - alias: Play ambient music in WC in the day
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: input_select.room_wc_occupancy
      to: "Zajęty"
    condition:
      - condition: time
        before: '11:00'
        after: '6:00'
      - condition: state
        entity_id: media_player.wc
        state: 'off'
    action:
      - service: media_player.volume_set
        entity_id: media_player.wc
        data:
          volume_level: 0.3
          
      - service: media_player.play_media
        data:
          entity_id: media_player.wc
          media_content_type: PLAYLIST
        data_template:
          media_content_id: >
            {{ [ "http://dcs-193-111-38-243.atmcdn.pl/sc/o2/Eurozet/live/antyradio.livx?audio=5" ] | random}}
  
  
  - alias: Play ambient music in WC in the morning
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: input_select.room_wc_occupancy
      to: "Zajęty"
    condition:
      - condition: time
        before: '20:00'
        after: '11:00'
      - condition: state
        entity_id: media_player.wc
        state: 'off'
    action:
      - service: media_player.volume_set
        entity_id: media_player.wc
        data:
          volume_level: 0.2
      
      - service: media_player.play_media
        data:
          entity_id: media_player.wc
          media_content_type: PLAYLIST
        # "http://somafm.com/groovesalad130.pls", "http://somafm.com/dronezone130.pls", 
        data_template:
          media_content_id: >
            {{ [ "http://chi-kat-01.cdn.eurozet.pl:8902/listen.pls"  ] | random }}
  
  - alias: Stop ambient music in WC
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_select.room_wc_occupancy
        to: "Pusty"
        for:
          minutes: 1
      - platform: state
        entity_id: input_select.room_wc_occupancy
        to: "Nieznany"
        for:
          minutes: 1
    
    action:
      - service: media_player.turn_off
        data:
          entity_id: media_player.wc
  
  - alias: Turn WC MLED on
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.d_wc
        to: 'on'
      - platform: state
        entity_id: input_select.room_wc_occupancy
        to: "Zajęty"
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.l_wc
          state: 'off'
    action:
      - service: light.turn_on
        data:
          entity_id:
            - light.l_wc
            
  - alias: Turn WC light off
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: input_select.room_wc_occupancy
      to: "Pusty"
      for:
        minutes: 1
    action:
      - service: light.turn_off
        data:
          entity_id:
            - light.l_wc
        
      
      
